__author__ = 'bocian'

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum
of the even-valued terms.

'''
data = [0]
count = 1
while max(data) < 4000000:                              # while loop working when max(data) is lower than 4M

    if count == 1 or count == 2:
        data.append(count)

    else:
        data.append(data[count-1]+data[count-2])        #to list 'data' added next fib number

    count+=1

score = 0
for x in range(0,len(data)-1):                          # function adding all even numbers in list 'data'
    if data[x]%2 == 0:
        score+=data[x]

print(data)
print(score)